# Copyright 2018 Province of British Columbia
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and limitations under the License.

#Set of scripts for processing wesp data for wespr
# Raw survey 123 field and stressor data
# Raw survey 123 manual office question data - used when a complete set of office data has not been generated by WESP_OF
#

source("header.R")

#Set the EcoProvince and name of the Survey 123 file name - it needs to be in the 'data' directory
#set up abbreviations and directory locations for EcoProvinces
WetlandAreaL<-list('SIM_Base',c('Taiga_Planes_Base','Boreal_Plains_Base'),
                   'Sub_Boreal','GD_Base','GD_Base_Est','Sub_Boreal_PEM','SI_Base')
WetlandAreaDirL<-c('SIM_Base','Taiga_Boreal_Plains',
                   'Sub_Boreal','GD_Base','GD_Base_Est','Sub_Boreal_PEM','SI_Base')
WetlandAreaShortL<-c('SIM','TBP',
                     'SB','GD','GD_Est','SB_PEM','SI')
EcoPNL<-list("SOUTHERN INTERIOR MOUNTAINS",c("BOREAL PLAINS","TAIGA PLAINS"),
             "SUB-BOREAL INTERIOR","GEORGIA DEPRESSION","GEORGIA DEPRESSION","SUB-BOREAL INTERIOR","SOUTHERN INTERIOR")

#Select an EcoProvince(s)
#one of: 1-SIM, 2-TBP, 3-SB, 4-GD, 5-GD_Est, 6-SB_PEM, 7-SI

EcoPN<-7

WetlandArea<-WetlandAreaL[EcoPN]
WetlandAreaDir<-WetlandAreaDirL[EcoPN]
EcoP<-WetlandAreaShortL[EcoPN]
WetlandEcoPName<-as.character(EcoPNL[EcoPN])
#For Plains use:
# WetlandEcoPName<-c("BOREAL PLAINS","TAIGA PLAINS")

#Survey 123 reference data file
file_123<-'combinedfield_survey123_01.09.2026.xls'


#Survey123 field and stress data:
#Load Survey123 field data from file
source("Load_Survey123_Field.R")
#Clean Survey123 field data￼
source("Clean_Survey123_Function.R")
source("Clean_Survey123_Stressor.R")


#If aggregated office data has not been exported from WESP_OF
#Load manual office data and clean
source('Load_Survey123_M_OF.R')
source("Clean_Survey123_M_OF.R")


#Collate function, stressor, manual data with automated Office Data
source("Clean_Collate_F_S_OF.R")

#Run wespR on data, normalize scores and run Jenks breaks
source('Analysis_wespR.R')

#Other - reading pre-compiled excel based batch calculator
source('Load_BatchCalculator.R')

